### PR TITLE
Python example

### PR DESCRIPTION
**Pull request by patemotiv**

### CODE REVIEW

**Review by hoangphamemotiv — APPROVED** [review]

**Comment by nguoithichkhampha** [comment]
Why don't use async method of python ? I like code example from Mat. I think we should base on this code and modify/add some new rather than replace it.

**Comment by hoangphamemotiv** [comment]
> 
> 
> Why don't use async method of python ? I like code example from Mat. I think we should base on this code and modify/add some new rather than replace it.

**Comment by hoangphamemotiv** [comment]
> 
> 
> Why don't use async method of python ? I like code example from Mat. I think we should base on this code and modify/add some new rather than replace it.

yep. Mat code is nice to me also. btw, i also see Tan code is clear and good . uhm. in pytho does user often use async function or not? a @tanpv .

**Comment by NguyenDuyToan** [comment]
@nguoithichkhampha Matt was using websockets libary, which is based on asyncio. While the new updates replace it with websocket-client, which's synchronous library. Working with synchronous functions always easier.

**Comment by nguoithichkhampha** [comment]
Imagine developer is using our cortex example in their project. now, we change the method handle data from async to sync. this is big change and they will not like it. Agree, sync method is easier but async has more useful feature. Especially for a real project.

**Comment by tanpv** [comment]
@nguoithichkhampha , after this code is approve and merge, the original code from Mat

> Imagine developer is using our cortex example in their project. now, we change the method handle data from async to sync. this is big change and they will not like it. Agree, sync method is easier but async has more useful feature. Especially for a real project.

@nguoithichkhampha , after this code is merged, we will still keep original Mat code and put to folder "async"

**Comment by nguoithichkhampha** [comment]
> @nguoithichkhampha , after this code is approve and merge, the original code from Mat\

It's fine if we explain more details in file README and I see in this PR file example.py deleted. not move to another folder.

**Comment by tanpv** [comment]
> > @nguoithichkhampha , after this code is approve and merge, the original code from Mat\
> 
> It's fine if we explain more details in file README and I see in this PR file example.py deleted. not move to another folder.

hi @nguoithichkhampha , added "async" folder and note to README for user which need for async code

**Review by nguoithichkhampha — APPROVED** [review]

**Pull request merged**
